### ISSUE TITLE
Conflict with Olark due to language attribute

### ISSUE THREAD

**Issue by andrewboni** [pc035860/angular-highlightjs#36]
Hi, we use [Olark](http://olark.com/) on our site in order to chat with users. Seems that Olark injects the following code:

```html
<script language="javascript" id="...
```

Angular highlightjs is also looking for this `language=` directive, which causes a conflict:
```
 Exception  Error: [$compile:ctreq] http://errors.angularjs.org/1.2.27/$compile/ctreq?p0=hljs&p1=language
```
```
Controller 'hljs', required by directive 'language', can't be found!
```

Any thoughts on how to properly resolve this? Thanks!

**Comment by stormbytes** [comment]
I came across a similar issue using 'source' attribute on an unrelated DOM element. I was baffled by the hljs error: 

``` 
Controller 'hljs', required by directive 'source', can't be found!
```

The directives need to have less ambiguous naming so as not to conflict with common attributes. A designated prefix would likely be a good solution. Let me know if you want help with this and I'll fork the repo.

**Comment by stormbytes** [comment]
FY: until this is resolved, avoid using element-attributes:

'include'
'source'
'language'

**Comment by pc035860** [comment]
Hi @stormbytes 

The issue can be easily resolved through setting the `hljs` controller requirement to be optional in those directives. But I'm also considering prefixing directive names with `hljs-`.

Do you think I should rename **all** related directive/attribute names or just directive names?

#### directive names
- language
- source
- include

#### attributes
- compile
- escape
- no-escape
- onhighlight

**Comment by pc035860** [comment]
Hey @andrewboni , **v0.3.3** should work without errors now.

**Comment by andrewboni** [comment]
Great- taking a look now.

**Comment by stormbytes** [comment]
Def a better idea to prefix attr-names

**Comment by andrewboni** [comment]
@pc035860 seems to be working- thanks for the fast resolution! Will let you know if I encounter anything else.

**Comment by andrewboni** [comment]
+1 agreed
