### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by kentcdodds** [pc035860/angular-highlightjs#38]
Would love to have this on npm so I can npm install it. :-)

![screen shot 2015-01-24 at 11 21 16 am](https://cloud.githubusercontent.com/assets/1500684/5888415/28f209c8-a3bb-11e4-91f4-dcddee20b985.png)

**Comment by pc035860** [comment]
It would be great to be able to install with npm, under the condition that I've add support for [browserify](http://browserify.org/), which works really well with `npm install` in my opinion.
Gonna look into it in couple of days. Thanks for the advice!

**Comment by pc035860** [comment]
Published!!! After finishing #39
