### ISSUE TITLE
Request: Line numbers

### ISSUE THREAD

**Issue by martinvelez** [pc035860/angular-highlightjs#41]
How can you display line numbers?

**Comment by pc035860** [comment]
Code highlighting of this module depends on [highlight.js](https://github.com/isagalaev/highlight.js).
And it seems that line numbers won't be added until they change their mind.

Please read:
http://highlightjs.readthedocs.org/en/latest/line-numbers.html

**Comment by martinvelez** [comment]
Fair enough.
