### ISSUE TITLE
ngmodules.org - include 'npm install angular-highlightjs'

### ISSUE THREAD

**Issue by juliusakula** [pc035860/angular-highlightjs#44]
[The ngmodules page](http://ngmodules.org/modules/angular-highlightjs), The Getting Started section, I think should contain: 

> `npm install angular-highlightjs`

I didn't read anywhere that this would install the directive, so I pretty much guessed and confirmed it was the same (it works). Just a suggestion for the ngmodules page which advertises this git repo and is the first google hit

Also, since this is such a short github issue I'm shamelessly going to plug my [markdown editor/renderer](http://juliusakula.github.io/editor/#/) that I made. this suggestion was for a change to a readme file anyway :P

**Comment by pc035860** [comment]
Hey thanks @juliusakula !
The npm support was released on v0.4.0, and I forgot to add it to README.

**Comment by pc035860** [comment]
BTW, I also updated the page on ngmodules, hope that would help people better understand the module.
It's so terrible that ngmodules' page doesn't support git-flavored markdown. :weary:

**Comment by juliusakula** [comment]
as an aside, I couldn't get angular-highlightjs to work with angular-md. my project is also open source so I can convienently link to the revelant files - so, quick question with context, if you look at my[src/views/hompage.tpl.hmtl](https://github.com/juliusakula/editor/blob/master/src/views/homepage.tpl.html) you can see the rendered markdown is pretty much:

<md ng-model="text"></md>

Is there a way I can have the $scope.text variable have the syntax highlighting in the same manner?

**Comment by pc035860** [comment]
It's like

```html
<div hljs source="text"></div>
```

I guess ?
