### ISSUE TITLE
Problem with .nohightlight class 

### ISSUE THREAD

**Issue by cassc** [pc035860/angular-highlightjs#45]
`<div class="col-lg-8" hljs language="java" source="s.content.taggedSource"></div>`
For the above html code, my `{{s.content.taggedSource}}` contains `<a href='#lntarget' class='nohighlight'>linkfrom</a>`, I'd expect an html link to created, however I get the raw text.

**Comment by pc035860** [comment]
According to https://highlightjs.org/usage/
I think the `nohighlight` class is just to prevent the auto-detected HTML strcture

```html
<pre><code> ... </code></pre>
```

from being highlighted, rather than providing a partially disabling highlight feature?
