### ISSUE TITLE
auto detect over rides manually specified language using ngRepeat

### ISSUE THREAD

**Issue by pcnate** [pc035860/angular-highlightjs#50]
Using the following line:

    <div hljs="" source="'$project->set(\'parameter\', \'value\');'" language="php"></div>

I am expecting:

    <code class="hljs php"><span class="hljs-variable">$project</span>-&gt;set(<span class="hljs-string">"parameter"</span>, <span class="hljs-string">"value"</span>);</code>

Instead, I am getting:

    <code class="hljs bash php"><span class="hljs-variable">$project</span>-&gt;set(<span class="hljs-string">"parameter"</span>, <span class="hljs-string">"value"</span>);</code>

**Comment by pc035860** [comment]
Hi @pcnate ,

I can't reproduce the issue. Here's the plunk.
http://plnkr.co/edit/WNujp5wA4GMjIQ7BuPmZ?p=preview

Can you fork it and try to reproduce the issue?

**Comment by pcnate** [comment]
It appears to be related to using ng-repeat="code in arrayOfCode"

    <div ng-repeat="code in phpCode track by $index">
      <div hljs="" source="code" language="php"></div>
    </div>


http://plnkr.co/edit/ekMJmrxWK9CpJtjhH3XK?p=preview

**Comment by pc035860** [comment]
OK, I'll look into it.

**Comment by pc035860** [comment]
The fix for #35 actually also fixed the issue. Will release a new version later today.
