### ISSUE TITLE
Support custom initialization

### ISSUE THREAD

**Issue by adaam2** [pc035860/angular-highlightjs#51]
Apologies if this issue has been raised before, but I couldn't find it! The Highlight.js documentation ([here](https://highlightjs.org/usage/)) provides the below example for highlighting code that doesn't use `<code>` or `<pre>` tags:

```
$('div.code').each(function(i, block) {
  hljs.highlightBlock(block);
});
```

How can we do this in angular-highlightjs?

**Comment by pc035860** [comment]
Hi @adaam2,

angular-highlightjs is just a set of directives, and the example you gave seems like you just need to call Highlight.js yourself. So I suggest that you can make your own directive with Highlight.js.

BTW, the Highlight.js is also available as an Angular service called `hljsService`.
https://github.com/pc035860/angular-highlightjs/blob/master/src/angular-highlightjs.js#L20

And you can call `hljsServiceProvider.setOptions` in configuration phase to change some settings.

**Comment by adaam2** [comment]
HI @pc035860 Thanks for the info, will look into that.
