### ISSUE TITLE
Bower still at 0.4.3

### ISSUE THREAD

**Issue by vovafeldman** [pc035860/angular-highlightjs#53]
Can you please bump the bower version to 0.5?

**Comment by pc035860** [comment]
@vovafeldman Just updated the bower version and released v0.5.1
Thanks for your report! Closing the issue.

**Comment by vovafeldman** [comment]
I've tried to run a package update and it didn't work, is there some delay till it propagates to the repo?

**Comment by pc035860** [comment]
Yeah, there might be some delay. And it seems updated now. Please try again.

If you still unable to update, may be you should update the version in your bower.json to allow it to install the version newer than 0.4.x.

http://stackoverflow.com/questions/19030170/what-is-the-bower-version-syntax

**Comment by vovafeldman** [comment]
Cool. Btw - thanks for adding the `source` directive, found it very useful!
