### ISSUE TITLE
Add highlightjs to dependencies

### ISSUE THREAD

**Issue by asnowwolf** [pc035860/angular-highlightjs#54]
This package is dependent on highlightjs but not in bower.json's "dependencies" field.

**Comment by pc035860** [comment]
Hi @asnowwolf ,

Though the highlightjs dependency is actually removed in #28 , it seems so many people asking about this.
So I guess I'll just add it back this weekend. Thanks for the opinion.

**Comment by pc035860** [comment]
Well, I changed my mind after checking out on [the bower package's github repo](https://github.com/components/highlightjs).

It has one huge packed highlight.js with all languages included, and usually you'll only use one or two of them. This adds so much overhead to the network transfer and javascript parsing.

Size difference:

- [fully packed](https://raw.githubusercontent.com/components/highlightjs/master/highlight.pack.min.js): 438KB
- [basic](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.0.0/highlight.min.js): 42.4KB

So I recommend that you just stay with the suggested way to include highlight.js described in README.
> There's currently no official bower package of highlight.js ([see here](https://github.com/isagalaev/highlight.js/issues/182#issuecomment-29251147)). You should either build highlight.js yourself or use the [pre-built one on cdnjs](https://cdnjs.com/libraries/highlight.js).

Closing the issue.
