### ISSUE TITLE
Render Angular Expression Output

### ISSUE THREAD

**Issue by realph** [pc035860/angular-highlightjs#55]
Is it possible to render the output of an Angular expression? I'm trying to render an Angular object called `blob`, but when I put it inside a `<div>` with an attribute of `hljs`, it prints the curly-braced expression rather than the output of that expression.

**This:**

    <div hljs>{{ blob }}</div>

**Outputs this:**

    <div hljs>{{ blob }}</div>

**When it should output this:**

    "name": {
      "first": "Krystal",
      "last": "Osborn"
    }

Any idea on how to do this with angular-highlightjs?

Any help is appreciated. Thanks in advance!

**Comment by pc035860** [comment]
Hi @realph ,

I've modified the demo in the README a bit.
http://plnkr.co/edit/CdwxGQ?p=preview

Note that the `hljs-interpolate` makes the interpolation after highlighting, so it'll stay no-color.

**Comment by realph** [comment]
@pc035860 This doesn't seem to work with `ng-repeat`.

**Comment by pc035860** [comment]
@realph Can you provide an example of using `ng-repeat` with it?

**Comment by realph** [comment]
@pc035860 http://plnkr.co/edit/uIsX0hYmy981HUSopX0j?p=preview

**Comment by pc035860** [comment]
@realph The `editObject` in the original demo is a JSON string, so it won't work if your `item` is an object if you simply put them into `toPrettyJSON` method.

Here's a working version
http://plnkr.co/edit/EWMPcvGsa7wgIIfdocb4?p=preview

And I made a new example which does only what you're asking for
http://plnkr.co/edit/EWMPcvGsa7wgIIfdocb4

Check the examples about the usage of directives
http://pc035860.github.io/angular-highlightjs/example/#/hljs-source

**Comment by realph** [comment]
@pc035860 It doesn't format the JSON anymore though. Have a look here: http://plnkr.co/edit/ep4YMRR2VgHPKD621UBf?p=preview

**Comment by pc035860** [comment]
@realph The JSON formatting part is done using native browser `JSON` api.

So you can re-enable that simply feeding the number of spaces required as a parameter to the `$scope.toPrettyJSONFromObj` in html.

```html
<!-- from -->
<div hljs hljs-source="toPrettyJSONFromObj(item)" ng-repeat="item in items track by $index"></div>

<!-- to -->
<div hljs hljs-source="toPrettyJSONFromObj(item, 4)" ng-repeat="item in items track by $index"></div>
```

With JSON formatting
http://plnkr.co/edit/rD0ZNWW87isrWdDtnvsX?p=preview

Also check [JSON.stringify API on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

**Comment by realph** [comment]
@pc035860 Of course. I forgot to pass that parameter. Thanks for this!
