### ISSUE TITLE
Preserve br tags

### ISSUE THREAD

**Issue by NetanelBasal** [pc035860/angular-highlightjs#57]
I have br tags in my string, and I want them to be a real br and not show them in the code, how can I do this?

**Comment by pc035860** [comment]
Hi, if you're using hljs-source for the highlighting, you can just
pragmatically remove replace those br tags with newline character I think.
Netanel <notifications@github.com>於 2016年1月14日 週四，下午3:10寫道：

**Comment by pc035860** [comment]
Before you through the source into hljs-source.
Chih-Hsuan Fan <pc035860@gmail.com>於 2016年1月15日 週五，上午10:16寫道：
