### ISSUE TITLE
Highlight.js should be a dep

### ISSUE THREAD

**Issue by ltegman** [pc035860/angular-highlightjs#61]
Using angular-highlightjs crashes without, so the `package.json` should list it as a dep.

**Comment by pc035860** [comment]
Yeah, and I might also add `angular` as a dependency as well.

**Comment by pc035860** [comment]
https://github.com/pc035860/angular-highlightjs/releases/tag/v0.6.0
New release with new npm dependencies published.

Closing the issue.
