### ISSUE TITLE
Marking specific subset of source code in addition to highlighting

### ISSUE THREAD

**Issue by mcadariu** [pc035860/angular-highlightjs#64]
Hi, 

Thanks for the really useful library, great work. 

I'd like to ask for a little guidance to proceed, help appreciated. 

How can I use angular-highlightjs to "mark" a subset of the source code lines with yellow background? 

This JSFiddle shows what I mean, which works with highlight.js:
http://jsfiddle.net/tovic/059x3ygs/2/

Thanks,
Mircea

**Comment by pc035860** [comment]
Hi @mcadariu ,

It's not possible for current `angular-highlightjs`, the stream-merging feature can only be invoked by `hljs.highlightBlock()`, and `angular-highlightjs`'s implementation uses `hljs.highlight()`.

**Comment by mcadariu** [comment]
Hi, 

Clear, many thanks for the helpful clarification! 

Greetings,
Mircea
