### ISSUE TITLE
Less-than-sign displaying as &lt;

### ISSUE THREAD

**Issue by ghost** [pc035860/angular-highlightjs#86]
This code...
```
<div hljs hljs-language="javascript">
  alert(1 < 2);
</div>
```
...is displayed as...

```
alert(1 &lt; 2);
```
Is there a way around this or is this a bug?
Plunker demo: https://plnkr.co/edit/RYkDoHgSwt5lyqBXFRvj

**Comment by pc035860** [comment]
Hi @JaredMathis 

Use `hljs-include` and place your code in a separate file or script tag to prevent your code from parsing by browser.

For more information, see #59

**Comment by ghost** [comment]
Thanks a lot @pc035860!!
