### ISSUE TITLE
Cant figure out hljs-source

### ISSUE THREAD

**Issue by jacobgranberry** [pc035860/angular-highlightjs#91]
Hey there - pretty new to angular and cant for the life of me figure out hljs-source.   I have a modal that pops up and renders code.  I need that rendered code to be highlighted.  I've tried everything but I feel like it should be simple!  I would appreciate any help!

```
<div class="modal-body">
       <div><pre><code>{{currentPost.code}}</code></pre></div>
</div>
```

**Comment by pc035860** [comment]
Try this

```html
<div class="modal-body">
  <div hljs hljs-source="currentPost.code"></div>
</div>
```

**Comment by jacobgranberry** [comment]
holy crap that worked! thanks for the quick response, i really appreciate it!
